# Before upgrading check that everything is available on all tier1 targets here:
# https://rust-lang.github.io/rustup-components-history
[toolchain]
channel = "nightly-2025-01-01"
targets = ["wasm32-unknown-unknown", "x86_64-unknown-linux-gnu"]
components = ["rust-src", "rustfmt", "clippy"]