# https://github.com/GoogleChromeLabs/wasm-bindgen-rayon/issues/11
[build]
filehash = false
pattern_script = '''
<script type="module">import init, { initThreadPool} from '{base}{js}';await init('{base}{wasm}'); await initThreadPool(1);</script>
'''
#navigator.hardwareConcurrency

[serve]
tls_key_path = "./localhost-key.pem"
tls_cert_path = "./localhost.pem"

[serve.headers]
# https://github.com/trunk-rs/trunk/tree/main/examples/wasm_threads
"cross-origin-embedder-policy"= "require-corp"
"cross-origin-opener-policy"= "same-origin"
"cross-origin-resource-policy"= "same-site"
