[package]
name = "shaderwheels-logic"
version = "0.1.0"
edition = "2024"

[dependencies]
openidconnect = "4.0.1"
pollster = "0.4.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
wgpu = {version="25.0.2", features = ["webgl"]}
